name: On Pull Request

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Task
        uses: illbjorn/setup-task@main

      - name: Lint
        shell: bash
        run: task lint
